extends Node
class_name ThreatComponent
## The aggro table. Lives on enemies; the Enforcer plays against it.
##
## Threat is generated by damage and healing, multiplied by the ability's
## own `threat_mult` and by the Enforcer's passive aura. A taunt does not
## add threat -- it forces the leader for a fixed window, which is what
## makes Dart Pull a *pull* rather than a damage race.

signal leader_changed(new_leader: Node)

@export var heal_threat_share: float = 0.5
@export var decay_per_second: float = 0.0

var _table: Dictionary = {}          # Node -> float
var _forced_leader: Node = null
var _forced_until: float = 0.0
var _leader: Node = null

func _process(delta: float) -> void:
	if _forced_leader != null and _now() >= _forced_until:
		_forced_leader = null
	if decay_per_second > 0.0:
		for unit in _table.keys():
			_table[unit] = maxf(0.0, _table[unit] - decay_per_second * delta)
	_recompute_leader()

func add_threat(unit: Node, amount: float) -> void:
	if unit == null or amount == 0.0:
		return
	_table[unit] = float(_table.get(unit, 0.0)) + amount
	_recompute_leader()

func taunt(unit: Node, duration: float) -> void:
	if unit == null:
		return
	# A taunt also tops the table, so aggro does not snap straight back the
	# instant the forced window ends.
	var highest := 0.0
	for value in _table.values():
		highest = maxf(highest, value)
	_table[unit] = maxf(float(_table.get(unit, 0.0)), highest * 1.1 + 1.0)
	_forced_leader = unit
	_forced_until = _now() + duration
	_recompute_leader()

func get_leader() -> Node:
	if _forced_leader != null and is_instance_valid(_forced_leader) and not _is_dead(_forced_leader):
		return _forced_leader
	return _leader

func threat_of(unit: Node) -> float:
	return float(_table.get(unit, 0.0))

## Everyone's threat as a share of whoever is holding it. This is the
## number the HUD draws.
func threat_share(unit: Node) -> float:
	var leader := get_leader()
	if leader == null:
		return 0.0
	var top := float(_table.get(leader, 0.0))
	if top <= 0.0:
		return 0.0
	return threat_of(unit) / top

func forget(unit: Node) -> void:
	_table.erase(unit)
	if _forced_leader == unit:
		_forced_leader = null
	_recompute_leader()

func participants() -> Array:
	return _table.keys()

func _recompute_leader() -> void:
	var best: Node = null
	var best_value := -1.0
	for unit in _table.keys():
		if not is_instance_valid(unit) or _is_dead(unit):
			continue
		var value: float = _table[unit]
		if value > best_value:
			best_value = value
			best = unit
	if best != _leader:
		_leader = best
		leader_changed.emit(get_leader())

func _is_dead(unit: Node) -> bool:
	return unit.get("is_dead") == true

func _now() -> float:
	return float(Time.get_ticks_msec()) / 1000.0
